services:
  - type: web
    name: athlete-connection-mapper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn connection_tool:app
    envVars:
      - key: NEO4J_URI
        value: bolt://your-neo4j-instance:7687
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        fromDatabase:
          name: neo4j-credentials
          property: password